apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      # volumes:
      #   - name: azure-disk-user
      #     persistentVolumeClaim:
      #       claimName: user-pv-claim
      containers:
        # - env:
            # use secret in future
            # - name: ConnectionString
            #   value: 'data source=sql-user;database=azure-disk-user;user id=sa;password=password_here;'
            # - name: ConnectionString
            #   value: 'Server=tcp:out-of-the-park-sql-server.database.windows.net,1433;Initial Catalog=user-service-db;Persist Security Info=False;User ID=p3-admin;Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        - name: user-service
          image: outofthepark15226.azurecr.io/user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: user-http

        # - env:
        #   - name: ACCEPT_EULA
        #     value: "y" 
        #   - name: SA_PASSWORD
        #   #make this into secret
        #     value: password_here
        #   image: mcr.microsoft.com/mssql/server:2019-latest
        #   name: sql-user
        #   ports:
        #     - containerPort: 1433
        #   volumeMounts:
        #     - name: azure-disk-user
        #       mountPath: /var/opt/mssql/data

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-deployment
spec:
  ports:
    - name: user-service
      port: 80
      targetPort: user-http
  selector:
    app: user-service
  # type: LoadBalancer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: user-service-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: user-service.1c50b018f5784721b39b.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: user-service-deployment
          servicePort: 80
        path: /api/user(/|$)(.*)
      - backend:
          serviceName: user-service-deployment
          servicePort: 80
        path: /api/account(/|$)(.*)
      - backend:
          serviceName: user-service-deployment
          servicePort: 80
        path: /(/|$)(.*)
