apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: outoftheparkacr.azurecr.io/user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: user-http
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-deployment
  namespace: default
spec:
  ports:
    - name: user-http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: user-service
  type: ClusterIP