apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      volumes:
        - name: azure-disk-user
          persistentVolumeClaim:
            claimName: user-pv-claim
      containers:
        - env:
            
            - name: ConnectionString
              value: 'data source=sql-user;database=azure-disk-user;user id=sa;password=password_here;'
            # - name: ConnectionStrings__zipkin
            #   value: 'http://zipkin:9411/'
          name: user-service
          image: outofthepark15226.azurecr.io/user
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: user-http

        - env:
          - name: ACCEPT_EULA
            value: "y" 
          - name: SA_PASSWORD
          #make this into secret
            value: password_here
          image: mcr.microsoft.com/mssql/server:2019-latest
          name: sql-user
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: azure-disk-user
              mountPath: /user/storage
