apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: devops-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: devops-admin
  namespace: default
# ---
# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: deployment-admin
# rules:
# - apiGroups: ["extensions", "apps"]
#   resources: ["deployments", "secrets", "storageclasses"]
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]