apiVersion: v1
kind: Service
metadata:
  name: user-service-deployment
spec:
  ports:
    - name: user-service
      port: 80
      targetPort: user-http
  selector:
    app: user-service
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: sql-user-deployment
spec:
  selector:
    app: sql-user
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
