apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - name: user-service
      port: 80
      targetPort: user-service-http
  selector:
    app: user-service
  type: ClusterIP
