kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
     name: azure-disk-user
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  kind: dedicated
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pv-claim
  labels:
    app: sql-user
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi